### ISSUE TITLE
EcommPay iOS SDK on M1

### ISSUE THREAD

**Issue by ZuluTradeGR** [ITECOMMPAY/paymentpage-sdk-ios#1]
Hey, guys 

I get the following message on attempting to run our app on Simulator, containing your SDK v 1.8.1, on Mac OS 11.2.3 with Apple chip M1, regardless the SDK target (Simulator or Universal).
Please advice.

Dimitris A.
ZuluTrade Mobile

Module 'ecommpaySDK' was created for incompatible target arm64-apple-ios10.0
<img width="605" alt="Screenshot 2021-03-20 at 7 59 22 AM" src="https://user-images.githubusercontent.com/81004373/111860741-4bfb0e00-8952-11eb-9e86-6699e42ec78e.png">

**Comment by AlexeyKhrameev** [comment]
if problem will reproduce
Please open issue again
