### ISSUE TITLE
Release 1.9.1 is not available on Cocoapods

### ISSUE THREAD

**Issue by Gray-Wind** [ITECOMMPAY/paymentpage-sdk-ios#3]
This release https://github.com/ITECOMMPAY/paymentpage-sdk-ios/releases/tag/1.9.1 is not available on CocoaPods, last release available there is 1.9.0

**Comment by Doomsday46** [comment]
Hi, this version was released on 04/22/2021. Please try to use the `pod update` command to update your dependencies.

**Comment by Gray-Wind** [comment]
```
❯ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Paymentpage-sdk-ios 1.9.1 (was 1.9.0)
Generating Pods project
[!] The plist file at path `/Users/user/projects/APP_NAME/Pods/Paymentpage-sdk-ios/ecommpaySDK-unzip-me/ecommpaySDK.xcframework/Info.plist` doesn't exist.
```

This is most probably because `ecommpaySDK.xcframework` in fact a zip archive. You could check it with `file ecommpaySDK.xcframework`.

**Comment by Doomsday46** [comment]
Hello, this issue has been resolved in version 1.9.2. Thank you for your feedback.

**Comment by Gray-Wind** [comment]
1.9.2 is not available on cocoapods.

**Comment by AlexeyKhrameev** [comment]
if problem reproduce
Please open issue again
