### ISSUE TITLE
MacBook Pro (13-inch, M1, 2020) - Xcode Simulator Issue

### ISSUE THREAD

**Issue by ZuluTradeGR** [ITECOMMPAY/paymentpage-sdk-ios#4]
On a MacBook Pro (13-inch, M1, 2020) 
with unchecked the option "Open using Rosetta" 
when I choose Simulator the compiler complains 
"Cannot find 'EcommpaySDK' in scope 
while in device is working properly.

![Screenshot 2021-08-02 at 11 17 51 AM](https://user-images.githubusercontent.com/81004373/127827878-6982290c-4069-4b95-aa63-1ec98e9733eb.png)
![Screenshot 2021-08-02 at 11 20 09 AM](https://user-images.githubusercontent.com/81004373/127828240-344d3b59-dc28-4aa8-9e9d-505a1ac9703e.png)

**Comment by AlexeyKhrameev** [comment]
if problem will reproduce
Please open issue again
