### ISSUE TITLE
Paymentpage-sdk-ios has a version conflict with the latest input-mask-ios (6.1.0)

### ISSUE THREAD

**Issue by AlexeiPozdnyakov** [ITECOMMPAY/paymentpage-sdk-ios#5]
Bug due to autoskip flag in new version of InputMask.
Please update depending

**Comment by ECOMMPAY** [comment]
Hello. We have fixed the issue in 1.11.4 release. Please update to that version.

**Comment by AlexeyKhrameev** [comment]
if problem reproduce
Please open issue again
