### ISSUE TITLE
The developer cannot be verified.

### ISSUE THREAD

**Issue by ZuluTradeGR** [ITECOMMPAY/paymentpage-sdk-ios#6]
"ecommpaySDK.framework"
cannot be opened because the
developer cannot be verified.

<img width="248" alt="Screenshot 2022-01-26 at 12 20 31 PM" src="https://user-images.githubusercontent.com/81004373/151146377-7e6ee371-76d7-482b-b81e-1ff08944f709.png">

**Comment by AlexeyKhrameev** [comment]
Hello
Can you explain what you want to do?

**Comment by AlexeyKhrameev** [comment]
solved
